### ISSUE TITLE
Can I use the library from python ?

### ISSUE THREAD

**Issue by ishandutta2007** [rivo/duplo#2]
python 3.3 and above

**Comment by rivo** [comment]
As much as any Go package can be called from Python. I haven't tried it myself but there are several pointers to this if you google something like "using go with python". There is nothing special that makes `duplo` different from most other Go packages.

**Comment by ishandutta2007** [comment]
already have. thanks anyways.

**Comment by ishandutta2007** [comment]
Thanks for your kind reply and will remain grateful for teaching me how to google.

**Comment by rivo** [comment]
Sorry I can't be of more help. If you have more questions specifically about this package, feel free to open an issue any time.
