### ISSUE TITLE
Is sthere a way  to retrieve the hash for an ID from a store?

### ISSUE THREAD

**Issue by mohangk** [rivo/duplo#3]
Hello, apologies if this is not the best way to reach out, was just wondering if there is a suggested way to retrieve a Hash that had been added to a Store. 

The use case is for comparing images in 2 separate directories. I hope to create a store of all images in dir1 as store1 and images in dir2 as store2. The stores are then compared by iterating over all the IDs of one store1 , retrieving the Hash for an ID and Querying it against store2. And then doing it the other way around.  Hope this makes sense. Any input is greatly appreciated.

**Comment by rivo** [comment]
Currently, there isn't such a function. The hashes are not saved directly in the store, at least not in one piece. Each part of the hash determines the search path in the tree. I suppose one could re-engineer the hash from that search path but it would be difficult.

I would suggest that one you generate the stores, you also save the hashes in a separate map for later.

**Comment by mohangk** [comment]
Thanks, for the information and useful suggestion.
