### ISSUE TITLE
best practices for persisting data?

### ISSUE THREAD

**Issue by Carseason** [rivo/duplo#5]
Is there any best solution?

**Comment by rivo** [comment]
I'm not aware of any "best" solution. In my own project, I have at most about a million pictures in a duplo store and I use the `GobEncode` and `GobDecode` methods to save to and read from a file. But you obviously cannot make changes during that time. And it may not scale well to your needs. It works for me, though.

I have been thinking about using a cache library like [Ristretto](https://github.com/dgraph-io/ristretto) for duplo. But this would require some sophisticated changes to the architecture. It's certainly nothing that works out of the box.

**Comment by Carseason** [comment]
thank you very much for your work, I wish the storage would take up less running memory, do you have a baseline memory usage analysis of millions of photos?  I'm using it on an embedded device
sorry, my English is not very good

**Comment by rivo** [comment]
Just checked and found that some of the stores actually contain about 2 million images. Gob-encoded and gzipped, they require around 500MB of disk space.

**Comment by Carseason** [comment]
cool! I'm already using him on Nas
